const projects = [
  {
    id: "agn-isimylek",
    title: "ĮSIMYLĖK",
    category: "music",
    client: "AGN",
    year: "2024",
    role: "producer & editor",
    description: "music video description",
    thumbnail: "assets/images/projects/agn-1.jpg",
    youtubeId: "4tBiw6oHTYc",
    orientation: "landscape",
    featured: false
  },
  {
    id: "agn-only-the-beginning",
    title: "ONLY THE BEGINNING",
    category: "music",
    client: "AGN",
    year: "2026",
    role: "producer & editor",
    description: "music video description",
    thumbnail: "assets/images/projects/agn-2.jpg",
    youtubeId: "bFPngcmhN3o",
    orientation: "landscape",
    featured: true
  },
  {
    id: "agn-picture-perfect",
    title: "PICTURE PERFECT",
    category: "music",
    client: "AGN, MURZINAS, ELZZSEVENTEEN",
    year: "2025",
    role: "producer & editor",
    description: "music video description",
    thumbnail: "assets/images/projects/agn-3.jpg",
    youtubeId: "oMtp5lLzVDk",
    orientation: "landscape",
    featured: false
  },
  {
    id: "xkhen-jessica-rabbit",
    title: "JESSICA RABBIT",
    category: "music",
    client: "xKHEN",
    year: "2024",
    role: "producer & editor",
    description: "music video description",
    thumbnail: "assets/images/projects/xkhen.jpg",
    youtubeId: "jxsM-0XOTFY",
    orientation: "landscape",
    featured: false
  },
  {
    id: "marta-gente-da-minha-terra",
    title: "GENTE DA MINHA TERRA",
    category: "fashion",
    client: "A.M.ART.E.A",
    year: "2025",
    role: "videographer & editor",
    description: "culture is not static; it lives, transforms, & inspires",
    thumbnail: "assets/images/projects/marta-1.jpg",
    youtubeId: "mEI1yRRRGLM",
    orientation: "vertical",
    featured: false
  },
  {
    id: "marta-adaptive-duality",
    title: "ADAPTIVE DUALITY",
    category: "fashion",
    client: "A.M.ART.E.A",
    year: "2024",
    role: "videographer & editor",
    description: "nature blends with street fashion",
    thumbnail: "assets/images/projects/marta-2.jpg",
    youtubeId: "ZxQYJflmzao",
    orientation: "vertical",
    featured: false
  },
  {
    id: "saule-spaudzia-laukas",
    title: "SPAUDžIA | pt. 1",
    category: "fashion",
    client: "SAULEX",
    year: "2024",
    role: "videographer & editor",
    description: "laukas",
    thumbnail: "assets/images/projects/saule-1.jpg",
    youtubeId: "9TFJixJP3ko",
    orientation: "vertical",
    featured: true
  },
  {
    id: "saule-spaudzia-runway",
    title: "SPAUDžIA | pt. 2",
    category: "fashion",
    client: "SAULEX",
    year: "2024",
    role: "videographer & editor",
    description: "runway",
    thumbnail: "assets/images/projects/saule-2.jpg",
    youtubeId: "Ci9gCO6qv0k",
    orientation: "vertical",
    featured: false
  },
  {
    id: "saule-spaudzia-red",
    title: "SPAUDžIA | pt. 3",
    category: "fashion",
    client: "SAULEX",
    year: "2024",
    role: "videographer & editor",
    description: "red",
    thumbnail: "assets/images/projects/saule-3.jpg",
    youtubeId: "yoM7rRitX0k",
    orientation: "vertical",
    featured: false
  },
  {
    id: "agn-event",
    title: "4 HOURS UNTIL",
    category: "events",
    client: "AGN",
    year: "2025",
    role: "editor",
    description: "behind the scenes of the Layer Off fashion show with agn",
    thumbnail: "assets/images/projects/agn-4.jpg",
    youtubeId: "MZ3RdwFqnQg",
    orientation: "landscape",
    featured: false
  },
  {
    id: "pdf",
    title: "PUSėS DAINOS FESTIVALIS",
    category: "events",
    client: "PDF",
    year: "2025",
    role: "videographer & editor",
    description: "description",
    thumbnail: "assets/images/projects/pdf.jpg",
    youtubeId: "trqYsAs7-ZQ",
    orientation: "vertical",
    featured: true
  },
  {
    id: "nfs",
    title: "SIX.",
    category: "events",
    client: "NFS",
    year: "2024",
    role: "videographer & editor",
    description: "aftermovie for the final New Fashion Society fashion show",
    thumbnail: "assets/images/projects/nfs.jpg",
    youtubeId: "CZy_WVZe9wE",
    orientation: "vertical",
    featured: false
  },
  {
    id: "kitokie-kitokiems",
    title: "KITOKIE KITOKIEMS",
    category: "events",
    client: "KITOKIE KITOKIEMS, UNO.",
    year: "2024",
    role: "videographer & editor",
    description: "promo for an event hosted by the dj collective Kitokie Kitokiems",
    thumbnail: "assets/images/projects/kitokie-kitokiems.jpg",
    youtubeId: "Uu3mrc9xrlQ",
    orientation: "vertical",
    featured: false
  },
  {
    id: "ginger-aardbei",
    title: "GINGER AARDBEI",
    category: "events",
    client: "GINGER AARDBEI",
    year: "2025",
    role: "videographer & editor",
    description: "aftermovie for a women's empowerment brunch hosted by Ginger Aardbei",
    thumbnail: "assets/images/projects/ginger-aardbei.jpg",
    youtubeId: "epj-6kPReFc",
    orientation: "vertical",
    featured: false
  },
  {
    id: "obscuur",
    title: "OBSCUUR x ADE",
    category: "events",
    client: "OBSCUUR",
    year: "2025",
    role: "editor",
    description: "promo for an event hosted by Obscuur at Amsterdam Dance Event",
    thumbnail: "assets/images/projects/obscuur.jpg",
    youtubeId: "epj-6kPReFc",
    orientation: "vertical",
    featured: false
  },
  {
    id: "lucie",
    title: "LUCIE",
    category: "long-form",
    client: "FRAME25",
    year: "2024",
    role: "producer & editor",
    description: "this is a love letter to those who nurture the French spirit, full of confidence & cheap wine",
    thumbnail: "assets/images/projects/lucie.jpg",
    youtubeId: "GsJzImcZeKU",
    orientation: "horizontal",
    featured: false
  },
];