const projects = [
  {
    id: "project-01",
    title: "PLACEHOLDER MUSIC PROJECT 01",
    category: "music",
    client: "PLACEHOLDER CLIENT",
    year: "2026",
    role: "Director, cinematographer, editor",
    description: "PLACEHOLDER DESCRIPTION OF THE PROJECT AND YOUR CREATIVE CONTRIBUTION.",
    thumbnail: "assets/images/projects/project-01.jpg",
    youtubeId: "PLACEHOLDER_YOUTUBE_ID",
    orientation: "landscape",
    featured: true
  },
  {
    id: "project-02",
    title: "PLACEHOLDER FASHION PROJECT 01",
    category: "fashion",
    client: "PLACEHOLDER CLIENT",
    year: "2026",
    role: "Director and editor",
    description: "PLACEHOLDER DESCRIPTION OF THE PROJECT AND YOUR CREATIVE CONTRIBUTION.",
    thumbnail: "assets/images/projects/project-02.jpg",
    youtubeId: "PLACEHOLDER_YOUTUBE_ID",
    orientation: "vertical",
    featured: true
  },
  {
    id: "project-03",
    title: "PLACEHOLDER EVENT PROJECT 01",
    category: "events",
    client: "PLACEHOLDER CLIENT",
    year: "2025",
    role: "Camera operator and editor",
    description: "PLACEHOLDER DESCRIPTION OF THE PROJECT AND YOUR CREATIVE CONTRIBUTION.",
    thumbnail: "assets/images/projects/project-03.jpg",
    youtubeId: "PLACEHOLDER_YOUTUBE_ID",
    orientation: "landscape",
    featured: true
  },
  {
    id: "project-04",
    title: "PLACEHOLDER LONG FORM PROJECT 01",
    category: "long-form",
    client: "PLACEHOLDER CLIENT",
    year: "2025",
    role: "Director and cinematographer",
    description: "PLACEHOLDER DESCRIPTION OF THE PROJECT AND YOUR CREATIVE CONTRIBUTION.",
    thumbnail: "assets/images/projects/project-04.jpg",
    youtubeId: "PLACEHOLDER_YOUTUBE_ID",
    orientation: "landscape",
    featured: false
  },
  {
    id: "project-05",
    title: "PLACEHOLDER MUSIC PROJECT 02",
    category: "music",
    client: "PLACEHOLDER CLIENT",
    year: "2025",
    role: "Editor",
    description: "PLACEHOLDER DESCRIPTION OF THE PROJECT AND YOUR CREATIVE CONTRIBUTION.",
    thumbnail: "assets/images/projects/project-05.jpg",
    youtubeId: "PLACEHOLDER_YOUTUBE_ID",
    orientation: "landscape",
    featured: false
  },
  {
    id: "project-06",
    title: "PLACEHOLDER EVENT PROJECT 02",
    category: "events",
    client: "PLACEHOLDER CLIENT",
    year: "2025",
    role: "Videographer and editor",
    description: "PLACEHOLDER DESCRIPTION OF THE PROJECT AND YOUR CREATIVE CONTRIBUTION.",
    thumbnail: "assets/images/projects/project-06.jpg",
    youtubeId: "PLACEHOLDER_YOUTUBE_ID",
    orientation: "vertical",
    featured: false
  },
  {
    id: "project-07",
    title: "PLACEHOLDER FASHION PROJECT 02",
    category: "fashion",
    client: "PLACEHOLDER CLIENT",
    year: "2024",
    role: "Cinematographer",
    description: "PLACEHOLDER DESCRIPTION OF THE PROJECT AND YOUR CREATIVE CONTRIBUTION.",
    thumbnail: "assets/images/projects/project-07.jpg",
    youtubeId: "PLACEHOLDER_YOUTUBE_ID",
    orientation: "landscape",
    featured: false
  },
  {
    id: "project-08",
    title: "PLACEHOLDER EVENT PROJECT 03",
    category: "events",
    client: "PLACEHOLDER CLIENT",
    year: "2024",
    role: "Camera operator",
    description: "PLACEHOLDER DESCRIPTION OF THE PROJECT AND YOUR CREATIVE CONTRIBUTION.",
    thumbnail: "assets/images/projects/project-08.jpg",
    youtubeId: "PLACEHOLDER_YOUTUBE_ID",
    orientation: "landscape",
    featured: false
  },
  {
    id: "project-09",
    title: "PLACEHOLDER MUSIC PROJECT 03",
    category: "music",
    client: "PLACEHOLDER CLIENT",
    year: "2024",
    role: "Director and editor",
    description: "PLACEHOLDER DESCRIPTION OF THE PROJECT AND YOUR CREATIVE CONTRIBUTION.",
    thumbnail: "assets/images/projects/project-09.jpg",
    youtubeId: "PLACEHOLDER_YOUTUBE_ID",
    orientation: "vertical",
    featured: false
  },
  {
    id: "project-10",
    title: "PLACEHOLDER LONG FORM PROJECT 02",
    category: "long-form",
    client: "PLACEHOLDER CLIENT",
    year: "2024",
    role: "Cinematographer and editor",
    description: "PLACEHOLDER DESCRIPTION OF THE PROJECT AND YOUR CREATIVE CONTRIBUTION.",
    thumbnail: "assets/images/projects/project-10.jpg",
    youtubeId: "PLACEHOLDER_YOUTUBE_ID",
    orientation: "landscape",
    featured: false
  }
];